const EErrors = {
  LOGGING_ERROR: 1,
  INVALID_FIELDS_ERROR: 2,
  DATABASE_ERROR: 3,
  AUTHORIZATION_ERROR: 4,
  NOT_DATA_FOUND_ERROR: 5,
  EXPIRED_TIME_ERROR: 6,
  EXISTING_DATA_ERROR: 7
}

export default EErrors